backend:
  name: github
  repo: "realworldreact/jamcommerce"
  branch: master # Branch to update (master by default)

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images" # src attribute for public images
publish_mode: editorial_workflow # uses PR's instead of direct commit messages

collections: # A list of collections the CMS should be able to edit
  - name: copy
    label: "Copy"
    create: true
    editor:
      preview: false
    files:
      - name: product_copy
        label: "Product Copy"
        file: "content/copy/product.yml"
        description: "Copy for the product page"
        fields:
          - name: callout
            label: Callout
            widget: object
            fields:

              - name: title
                label: Title
                widget: string

              - name: description
                label: Description
                widget: text

      - name: home_copy
        label: "Home Copy"
        file: "content/copy/home.yml"
        description: "Copy for the home page"
        fields:
          - name: prefooter
            label: "Above the Footer"
            widget: text

  - name: product
    label: Product
    path: '/product'
    slug: '{{name}}'
    folder: "content/collections/product"
    create: true
    fields:
      - name: name
        label: Name
        widget: string

      - name: description
        label: Description
        widget: markdown

      - name: details
        label: Details
        widget: list


      - name: price
        label: Price
        widget: number

      - name: sale
        label: Sale
        widget: number
        required: false

      - name: images
        label: Images
        widget: list
        fields:
          - name: name
            label: Name
            widget: string

          - name: alt
            label: Alt Text
            widget: string

          - name: image
            label: Image
            widget: image
